# Generated by Django 5.1.1 on 2024-10-06 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pot', models.DecimalField(decimal_places=2, max_digits=10)),
                ('datum', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Spieler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gesamtgewinn', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='EventTeilnahme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventgewinn', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poker.event')),
                ('spieler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poker.spieler')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='teilnehmer',
            field=models.ManyToManyField(through='poker.EventTeilnahme', to='poker.spieler'),
        ),
    ]
