# Generated by Django 5.1.1 on 2024-10-06 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spieler',
            name='date_of_first_participation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='spieler',
            name='gruendungsmitglied',
            field=models.BooleanField(default=False),
        ),
    ]
