# Generated by Django 5.1.1 on 2024-10-06 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0002_spieler_date_of_first_participation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
