# Generated by Django 5.1.1 on 2024-10-06 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0003_event_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='asop',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='gastgeber_spieler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastgeber_events', to='poker.spieler'),
        ),
        migrations.AlterField(
            model_name='event',
            name='teilnehmer',
            field=models.ManyToManyField(related_name='teilnahmen', through='poker.EventTeilnahme', to='poker.spieler'),
        ),
    ]
